name 'puppet-module-krb5'
version '0.4.0'
source 'git://github.com/emahags/puppet-module-krb5.git'
author 'emahags'
license 'Apache License, Version 2.0'
summary 'Manage krb5'
description 'Manage krb5'
project_page 'https://github.com/emahags/puppet-module-krb5'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
